In [ ]:
import numpy as np
import pandas as pd
import yfinance as yf
import math
from scipy import stats
!pip install xlsxwriter
import xlsxwriter

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
stocks=pd.read_csv('/content/drive/MyDrive/sp_500_stocks.csv')
stocks.head()

  Ticker
0      A
1    AAL
2    AAP
3   AAPL
4   ABBV

In [ ]:
symbol ='AAPL'
ticker=yf.Ticker('AAPL')
one_yr_change=ticker.info.get('52WeekChange','N/A')
one_yr_change

0.54248035

In [ ]:
my_coloumn=['Ticker','Price','One Year Returns','Number of Shares to buy']
final_dataframe=pd.DataFrame(columns=my_coloumn)
for symbol in stocks['Ticker']:
  ticker=yf.Ticker(symbol)
  price = ticker.info.get('currentPrice') or ticker.info.get('regularMarketPrice', 'N/A')
  one_yr_change=ticker.info.get('52WeekChange','N/A')
  newrow={
    'Ticker':symbol,
    'Price':price,
    'One Year Returns':one_yr_change,
    'Number of Shares to buy': 'N/A'

  }
  final_dataframe = pd.concat([final_dataframe, pd.DataFrame([newrow])], ignore_index=True)
final_dataframe

/tmp/ipykernel_2882/3307112329.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_dataframe = pd.concat([final_dataframe, pd.DataFrame([newrow])], ignore_index=True)
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANSS"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COG"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRC"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBI"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JNPR"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NLSN"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TWTR"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

    Ticker   Price One Year Returns Number of Shares to buy
0        A  114.96         0.033255                     N/A
1      AAL   13.85         0.189862                     N/A
2      AAP   57.95         0.168347                     N/A
3     AAPL  308.82          0.54248                     N/A
4     ABBV   215.7         0.161426                     N/A
..     ...     ...              ...                     ...
500    YUM  155.15         0.076758                     N/A
501    ZBH    85.5        -0.092453                     N/A
502   ZBRA  255.55        -0.133758                     N/A
503   ZION   62.12         0.302033                     N/A
504    ZTS   81.32        -0.510887                     N/A

[505 rows x 4 columns]

In [ ]:
final_dataframe = final_dataframe[final_dataframe['One Year Returns'] != 'N/A'].reset_index(drop=True)
final_dataframe.sort_values('One Year Returns', ascending=False, inplace=True)
final_dataframe=final_dataframe[:50]
final_dataframe

   Ticker    Price One Year Returns Number of Shares to buy
0     WDC   484.28         8.345427                     N/A
1      MU    751.0         6.792073                     N/A
2     STX   812.73         5.943443                     N/A
3    INTC   119.84          4.83163                     N/A
4     AMD   467.51         3.080918                     N/A
5     GLW   194.05          2.88722                     N/A
6    LRCX   305.35         2.637717                     N/A
7     ALB   171.58         1.918524                     N/A
8    AMAT   432.16         1.670457                     N/A
9     CAT   879.89         1.503172                     N/A
10   KLAC  1888.38         1.393202                     N/A
11    FTI    70.99         1.346777                     N/A
12    APA     38.8         1.241479                     N/A
13  GOOGL   382.97          1.21498                     N/A
14   GOOG   379.38         1.180595                     N/A
15   KEYS   346.56         1.135831                     N/A
16    NUE    232.0         1.121046                     N/A
17    PWR   723.44         1.113159                     N/A
18    HPE    37.58          1.09476                     N/A
19    HAL    41.47         1.076615                     N/A
20    NEM   107.64         1.042117                     N/A
21    CMI   639.55         0.960246                     N/A
22    BWA    65.82         0.958929                     N/A
23   AKAM   147.23          0.89023                     N/A
24    VLO   246.96         0.889373                     N/A
25   CSCO   120.41         0.888784                     N/A
26   JBHT   258.77         0.848357                     N/A
27    IVZ    27.05         0.832656                     N/A
28    ADI   397.07         0.830744                     N/A
29    FDX    394.2         0.793775                     N/A
30   CHRW   174.23         0.790647                     N/A
31   IPGP    119.0          0.77718                     N/A
32    BKR    66.06         0.774376                     N/A
33   AVGO   414.14         0.757437                     N/A
34   ILMN   144.41         0.750636                     N/A
35    TPR   138.49         0.711866                     N/A
36    NOV    20.81          0.69187                     N/A
37    SLB    57.28         0.688182                     N/A
38    TXN   309.21         0.687459                     N/A
39   ANET   154.03         0.665369                     N/A
40   ROST   234.81         0.661901                     N/A
41     DD    48.12         0.660269                     N/A
42      C   125.09          0.65748                     N/A
43    KSS    13.06         0.651075                     N/A
44     GS   996.73         0.618778                     N/A
45     GM    78.79         0.605011                     N/A
46   QCOM   238.16         0.602368                     N/A
47   EBAY   115.75         0.597874                     N/A
48    SEE    42.15         0.596591                     N/A
49    ADM    77.52         0.594078                     N/A

In [ ]:
port_size=input('ENTER VALUE OF YOUR PORTFOLIO')
try:
  val=float(port_size)
  print(val)
except ValueError:
  print('Enter a valid integer \n')
  port_size=input('ENTER VALUE OF YOUR PORTFOLIO')
  val=float(port_size)
  print(val)

1000000.0

In [ ]:
position_size=val/len(final_dataframe.index)
print(position_size)

20000.0

In [ ]:
for i in range(len(final_dataframe)):
    final_dataframe.loc[i, 'Number of Shares to buy'] = math.floor(position_size / final_dataframe.loc[i, 'Price'])
final_dataframe

   Ticker    Price One Year Returns Number of Shares to buy
0     WDC   484.28         8.345427                      41
1      MU    751.0         6.792073                      26
2     STX   812.73         5.943443                      24
3    INTC   119.84          4.83163                     166
4     AMD   467.51         3.080918                      42
5     GLW   194.05          2.88722                     103
6    LRCX   305.35         2.637717                      65
7     ALB   171.58         1.918524                     116
8    AMAT   432.16         1.670457                      46
9     CAT   879.89         1.503172                      22
10   KLAC  1888.38         1.393202                      10
11    FTI    70.99         1.346777                     281
12    APA     38.8         1.241479                     515
13  GOOGL   382.97          1.21498                      52
14   GOOG   379.38         1.180595                      52
15   KEYS   346.56         1.135831                      57
16    NUE    232.0         1.121046                      86
17    PWR   723.44         1.113159                      27
18    HPE    37.58          1.09476                     532
19    HAL    41.47         1.076615                     482
20    NEM   107.64         1.042117                     185
21    CMI   639.55         0.960246                      31
22    BWA    65.82         0.958929                     303
23   AKAM   147.23          0.89023                     135
24    VLO   246.96         0.889373                      80
25   CSCO   120.41         0.888784                     166
26   JBHT   258.77         0.848357                      77
27    IVZ    27.05         0.832656                     739
28    ADI   397.07         0.830744                      50
29    FDX    394.2         0.793775                      50
30   CHRW   174.23         0.790647                     114
31   IPGP    119.0          0.77718                     168
32    BKR    66.06         0.774376                     302
33   AVGO   414.14         0.757437                      48
34   ILMN   144.41         0.750636                     138
35    TPR   138.49         0.711866                     144
36    NOV    20.81          0.69187                     961
37    SLB    57.28         0.688182                     349
38    TXN   309.21         0.687459                      64
39   ANET   154.03         0.665369                     129
40   ROST   234.81         0.661901                      85
41     DD    48.12         0.660269                     415
42      C   125.09          0.65748                     159
43    KSS    13.06         0.651075                    1531
44     GS   996.73         0.618778                      20
45     GM    78.79         0.605011                     253
46   QCOM   238.16         0.602368                      83
47   EBAY   115.75         0.597874                     172
48    SEE    42.15         0.596591                     474
49    ADM    77.52         0.594078                     257

FOR A HIGH QUALITY MOMENTUM STRATEGY

In [ ]:
hqm_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'One-Year Price Return',
    'One-Year Return Percentile',
    'Six-Month Price Return',
    'Six-Month Return Percentile',
    'Three-Month Price Return',
    'Three-Month Return Percentile',
    'One-Month Price Return',
    'One-Month Return Percentile'
]